import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#2563eb',
    primaryContainer: '#dbeafe',
    secondary: '#059669',
    secondaryContainer: '#d1fae5',
    tertiary: '#7c3aed',
    tertiaryContainer: '#ede9fe',
    surface: '#ffffff',
    surfaceVariant: '#f8fafc',
    background: '#f8fafc',
    error: '#dc2626',
    errorContainer: '#fee2e2',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#1e40af',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#047857',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#5b21b6',
    onSurface: '#0f172a',
    onSurfaceVariant: '#64748b',
    onBackground: '#0f172a',
    onError: '#ffffff',
    onErrorContainer: '#b91c1c',
    outline: '#e2e8f0',
    outlineVariant: '#f1f5f9',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#1e293b',
    inverseOnSurface: '#f1f5f9',
    inversePrimary: '#60a5fa',
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#60a5fa',
    primaryContainer: '#1e40af',
    secondary: '#34d399',
    secondaryContainer: '#047857',
    tertiary: '#a78bfa',
    tertiaryContainer: '#5b21b6',
    surface: '#1e293b',
    surfaceVariant: '#334155',
    background: '#0f172a',
    error: '#f87171',
    errorContainer: '#b91c1c',
    onPrimary: '#1e40af',
    onPrimaryContainer: '#dbeafe',
    onSecondary: '#047857',
    onSecondaryContainer: '#d1fae5',
    onTertiary: '#5b21b6',
    onTertiaryContainer: '#ede9fe',
    onSurface: '#f1f5f9',
    onSurfaceVariant: '#94a3b8',
    onBackground: '#f1f5f9',
    onError: '#b91c1c',
    onErrorContainer: '#fee2e2',
    outline: '#475569',
    outlineVariant: '#334155',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#f1f5f9',
    inverseOnSurface: '#1e293b',
    inversePrimary: '#2563eb',
  },
};

// Default to light theme
export const theme = lightTheme;
