version: '3.8'

services:
  authentication:
    build:
      context: .
      dockerfile: services/authentication/Dockerfile
    ports:
      - "8005:8000"
    environment:
      POSTGRES_URL: postgresql://aicuser:aicpass@postgres:5432/aicsynergy
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-jwt-secret-change-in-production
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
